export const FETCH_ROBOT_REQUEST = 'FETCH_ROBOT_REQUEST';
export const FETCH_ROBOT_SUCCESS = 'FETCH_ROBOT_SUCCESS';
export const FETCH_ROBOT_FAILURE = 'FETCH_ROBOT_FAILURE';

export const MOVE_ROBOT_REQUEST = 'MOVE_ROBOT_REQUEST';
export const MOVE_ROBOT_SUCCESS = 'MOVE_ROBOT_SUCCESS';
export const MOVE_ROBOT_FAILURE = 'MOVE_ROBOT_FAILURE';

export const LEFT_ROBOT_REQUEST = 'LEFT_ROBOT_REQUEST';
export const LEFT_ROBOT_SUCCESS = 'LEFT_ROBOT_SUCCESS';
export const LEFT_ROBOT_FAILURE = 'LEFT_ROBOT_FAILURE';

export const RIGHT_ROBOT_REQUEST = 'RIGHT_ROBOT_REQUEST';
export const RIGHT_ROBOT_SUCCESS = 'RIGHT_ROBOT_SUCCESS';
export const RIGHT_ROBOT_FAILURE = 'RIGHT_ROBOT_FAILURE';

export const PLACE_ROBOT_REQUEST = 'PLACE_ROBOT_REQUEST';
export const PLACE_ROBOT_SUCCESS = 'PLACE_ROBOT_SUCCESS';
export const PLACE_ROBOT_FAILURE = 'PLACE_ROBOT_FAILURE';